name: Build Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.description=JABAS Website container
            org.opencontainers.image.authors=JABAS Team
          # list of Docker images to use as base name for tags
          images: |
            lcas.lincoln.ac.uk/jabas/jabas.ai
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,enable=${{ github.event_name != 'pull_request' }},value=latest
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
  
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}  
          cache-from: type=gha
          cache-to: type=gha,mode=max
